In [1]:
# import requests
# from IPython.core.display import HTML
# HTML(f"""
# <style>
# @import "https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css";
# </style>
# """)

# Linear Algebra using Python and Numpy
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to familiarise yourself with the concepts of linear algebra and how to use them in Numpy. The following topics will be covered:
- Performing matrix operations (elementwise operations, transpose, multiplication, inverse).
- Properties of matrix multiplication and inverse.
- Representing linear equations in matrix form.
- Solving linear equations using the matrix inverse.

<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li><li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li><li>
            <a href="#elem_mul">Task 3: Elementwise multiplication</a>
            </li><li>
            <a href="#inverses">Task 4: Inverses</a>
            </li><li>
            <a href="#inverse_prop">Task 5: Inverse properties</a>
            </li><li>
            <a href="#determinant">Task 6: The determinant</a>
            </li><li>
            <a href="#transpose">Task 7: Transpose</a>
            </li><li>
            <a href="#eqsys">Task 8: Solving linear equation system…</a>
            </li><li>
            <a href="#matmul">Task 9: Implementing matrix multiplica…</a>
            </li>
        </ul>
    </div>
</article>
The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [3]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---


In [4]:
np.subtract(A, B)

array([[ 17.        , -14.5       ,  14.33333333, -12.75      ],
       [ 12.5       , -10.66666667,  10.25      ,  -8.8       ],
       [  8.33333333,  -6.75      ,   6.2       ,  -4.83333333],
       [  4.25      ,  -2.8       ,   2.16666667,  -0.85714286]])


---
**Task 2 (easy): Multiplication properties👩‍💻**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html#numpy.dot)
 or the `@`
 operator).
2. Explain why the results are different.


---


In [5]:
ac = np.dot(A, C)#
ca = np.dot(C, A)

print(ac)
print(ca)
print('Are AC and CA equal? ' + str(np.array_equal(ac, ca)))
print('Matrix multiplication is not commutative')

[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
Are AC and CA equal? False
Matrix multiplication is not commutative



---
**Task 3 (easy): Elementwise multiplication👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators.


---


In [6]:
ac = A * C
print(ac)
print('''
The difference between * and @ is that * does elementwise multiplciation while @ takes the dot product
      
Elementwise multiplication is done by multiplying each index, e.g. a11 * c11 and so on
''')

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]

The difference between * and @ is that * does elementwise multiplciation while @ takes the dot product
      
Elementwise multiplication is done by multiplying each index, e.g. a11 * c11 and so on




---
**Task 4 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. _Hint: The question relates to the limitations of floating point numbers._


---


In [7]:
invA = np.linalg.inv(A)
invC = np.linalg.inv(C)

print(f'Inverse of matrix A: {invA}')
print(f'Inverse of matrix C: {invC}')
print(f'AA^-1: {np.dot(A, invA)}')
print(f'CC^-1: {np.dot(C, invC)}')
print('''
When the computer calcualtes a number, it only has a finite number of bits
      
This can lead to rounding errors when using floating point numbers, which is the reason why we 
didn't get the identity matrix in our calculations
''')

Inverse of matrix A: [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
Inverse of matrix C: [[   -72.           -225.            525.             42.        ]
 [  1260.           3675.          -8820.00000001   -630.        ]
 [ -3696.         -10710.00000001  25830.00000002   1764.        ]
 [  2700.           7830.00000001 -18900.00000001  -1260.        ]]
AA^-1: [[ 1.00000000e+00  0.00000000e+00  2.27373675e-13  0.00000000e+00]
 [-1.55431223e-15  1.00000000e+00  1.12532206e-13  3.10862447e-14]
 [ 1.29526020e-15 -3.44909286e-14  1.00000000e+00 -4.48530102e-14]
 [-5.99520433e-15  8.00629404e-14 -1.61585031e-13  1.00000000e+00]]
CC^-1: [[ 1.00000000e+00  2.27373675e-13  0.00000000e+00  5.68434189e-14]
 [ 2.99760217e-14  1.00000000e+00 -2.09832152e-13  2.58015831e-14]
 [-6.71808288e-14 -1.11454056e-13  1.00000000e+00  5.19831092e-14]
 [-1.03374099e-14  2.23278186e-15  1.67100901e-13  1.00000000e+00]]

When the co

### Properties

---
**Task 5 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---


In [8]:
invDinvE = np.dot(np.linalg.inv(D), np.linalg.inv(E))
invED = np.linalg.inv(np.dot(E, D))
invDE = np.linalg.inv(np.dot(D, E))

print(f'D^-1E^-1 = (ED)^-1 {np.allclose(invDinvE, invED)}')
print(f'D^-1E^-1 = (DE)^-1 {np.allclose(invDinvE, invDE)}')

D^-1E^-1 = (ED)^-1 True
D^-1E^-1 = (DE)^-1 False



---
**Task 6 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html#numpy.linalg.det)
.
2. Based on the results, determine which of the matrices have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html#numpy.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---


In [9]:
detA = np.linalg.det(A)
detB = np.linalg.det(B)
detC = np.linalg.det(C)
invA = np.linalg.inv(A)
# invB = np.linalg.inv(B)
invC = np.linalg.inv(C)

print('''
For a square matrix, and inverse matrix exists only if it as a non zero determinant
''')
print(f'Determinant of A: {detA}')
print(f'Inverse of A: {invA}')
print(f'Determinant of B: {detB}')
print(f'Inverse of B does not exists')
print(f'Determinant of C: {detC}')
print(f'Inverse of C: {invC}')



For a square matrix, and inverse matrix exists only if it as a non zero determinant

Determinant of A: 1.6534391534390412e-07
Inverse of A: [[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
Determinant of B: 0.0
Inverse of B does not exists
Determinant of C: 1.0498026371034301e-07
Inverse of C: [[   -72.           -225.            525.             42.        ]
 [  1260.           3675.          -8820.00000001   -630.        ]
 [ -3696.         -10710.00000001  25830.00000002   1764.        ]
 [  2700.           7830.00000001 -18900.00000001  -1260.        ]]



---
**Task 7 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.



---


In [10]:
print(f'(D^-1)^T == D^T^-1: {np.allclose(np.transpose(np.linalg.inv(D)), np.linalg.inv(np.transpose(D)))}')

(D^-1)^T == D^T^-1: True


## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$

where $A$ is the coefficient matrix, $x$ vector of unknowns, and $b$ is a vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$


---
**Task 8 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$

b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$

c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$

d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$

e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$

f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$


---


In [11]:
def solveLinearEquation(a, b):
    if np.linalg.det(a) == 0:
        print('No solution exists, determinant = 0')
        return None
    invA = np.linalg.inv(a)

    res = np.dot(invA, b)
    if len(res) == 2:
        print(f'x: {res[0]}, y: {res[1]}')
    if len(res) == 3:
        print(f'x: {res[0]}, y: {res[1]}, z: {res[2]}')

a = np.array([[2, 3], [1, 1]])
solveLinearEquation(a, np.array([-1, 0]))

a = np.array([[1, 0], [0, 1]])
solveLinearEquation(a, np.array([5, 7]))

a = np.array([[0, 1], [-2, -3]])
solveLinearEquation(a, np.array([-1, 2]))

a = np.array([[0, -3, 3], [0, -5, 3], [6, -6, 4]])
solveLinearEquation(a, np.array([0.5, 0.5, 1]))

a = np.array([[2, 3, 4], [1, 4, 1], [4, 5, 2]])
solveLinearEquation(a, np.array([2, -2, 3]))

a = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
solveLinearEquation(a, np.array([2, -2, 3]))


x: 1.0, y: -1.0
x: 5.0, y: 7.0
x: 0.5, y: -1.0
x: 0.05555555555555554, y: 0.0, z: 0.16666666666666669
x: 1.90625, y: -1.0625, z: 0.34375
No solution exists, determinant = 0


## Matrix multiplication
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is a new $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$

In other words, it is the dot product of the $i$’th row vector of $A$ and the $j$’th column vector of $B$.

---
**Task 9 (medium): Implementing matrix multiplication _(optional)_👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy’s built-in functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.



---


In [12]:
def matmul(a, b):
    # Implement this function
    ...
    
ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)

---
